import Link from 'next/link'

import { cn } from '@/lib/utils/cn'

/**
 * The word that names what a step produces. Rendered for assistive technology
 * only: the mono measured-blue treatment already reads as an output to a
 * sighted reader, and the site says "Output" nowhere else on the row.
 */
const outputLabel = 'Output:'

export type MethodStep = {
  /** Optional, where the approved copy records no name for the step. */
  title?: string
  /**
   * The step's own label, where the page has one ("Stage 1"). Replaces the
   * generated counter, so an approved coordinate is printed rather than
   * silently replaced by a number that happens to match it.
   */
  marker?: string
  /** The step, one paragraph per entry, in the order it is read. */
  body: readonly string[]
  /** The named artifact the step produces. */
  output?: string
  /** Where the step is delivered. */
  link?: { label: string; href: string }
}

/**
 * The numbered method list (canvas `_canvas.css` section 16, `.method`).
 *
 * The step number sits in the margin in mono and is generated by a CSS counter,
 * so the step titles form one left edge and the list reads as a procedure
 * rather than as a bulleted opinion. The counter is decorative: the ordered
 * list already carries the order to assistive technology, and a step that has
 * an approved label of its own prints that instead.
 */
export function MethodList({
  steps,
  ariaLabel,
  className,
}: {
  steps: readonly MethodStep[]
  ariaLabel?: string
  className?: string
}) {
  return (
    <ol className={cn('method', className)} aria-label={ariaLabel}>
      {steps.map((step) => (
        <li key={step.marker ?? step.title} data-marker={step.marker}>
          <div>
            {step.title ? <h3>{step.title}</h3> : null}
            {step.body.map((paragraph) => (
              <p key={paragraph}>{paragraph}</p>
            ))}
            {step.output || step.link ? (
              <p className="outrow">
                {step.output ? (
                  <span className="out">
                    <span className="sr-only">{outputLabel} </span>
                    {step.output}
                  </span>
                ) : null}
                {step.link ? (
                  <Link className="tlink" href={step.link.href}>
                    {step.link.label}
                  </Link>
                ) : null}
              </p>
            ) : null}
          </div>
        </li>
      ))}
    </ol>
  )
}
